import Head from 'next/head';
import { useState, useEffect } from 'react';
import { AiOutlinePlus } from 'react-icons/ai';
import Todo from '../components/Todo';
import { db } from './firebase';
import { query, collection, onSnapshot, updateDoc, addDoc, doc, deleteDoc } from 'firebase/firestore';

export default function Home() {
  const [todos, setTodos] = useState([]);
  const [input, setInput] = useState('');

  const createTodo = async (e) => {
    e.preventDefault(e);
    if (input === '') {
      alert('Please enter a valid todo');
      return;
    }
    await addDoc(collection(db, 'todos'), {
      text: input,
      completed: false,
    });
    setInput('');
  };

  useEffect(() => {
    const q = query(collection(db, 'todos'));
    const unsubscribe = onSnapshot(q, (querySnapshot) => {
      let todosArr = [];
      querySnapshot.forEach((doc) => {
        todosArr.push({ ...doc.data(), id: doc.id });
      });
      setTodos(todosArr);
    });
    return () => unsubscribe();
  }, []);

  const toggleComplete = async (todo) => {
    await updateDoc(doc(db, 'todos', todo.id), {
      completed: !todo.completed
    })
  }

  const deleteTodo = async (id) => {
    await deleteDoc(doc(db, 'todos', id));
  }

  return (
    <div className='h-screen w-screen p-4 bg-gradient-to-l from-[#a445b2] to-[#fa4299]'>
      <Head>
        <title>Todo&#39;s App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='bg-slate-100 max-w-[600px] w-full m-auto rounded-md shadow-xl p-4'>
        <h3 className='text-3xl font-bold text-center text-gray-800 p-2'>ToDo&#39;s</h3>
        <form className='flex justify-between' onSubmit={(e) => createTodo(e)}>
          <input
            type="text"
            placeholder='Add ToDo'
            className='border p-2 w-full text-xl rounded'
            value={input}
            onChange={(e) => setInput(e.target.value)}
          />
          <button className='border p-4 ml-2 bg-purple-600 text-white hover:bg-purple-700 transition rounded'>
            <AiOutlinePlus size={30} />
          </button>
        </form>
        <ul>
          {
            todos.map((todo, index) => (
              <Todo key={index} todo={todo} toggleComplete={toggleComplete} deleteTodo={deleteTodo} />
            ))
          }
        </ul>
        {todos.length < 1 ? '' : <p className='text-lg text-center p-2'>{`You have ${todos.length} todo's`}</p>}
      </div>
    </div>
  )
}